name: fhir_path
description: FHIRPath navigation and extraction language implemented in pure Dart to be used with base FHIR packages.
version: 0.12.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_path

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  fhir: ^0.12.0
  ucum: ^0.4.0
  petitparser: ^6.0.2

dev_dependencies:
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  lints: ^3.0.0
  test: ^1.25.2

