name: fhir_path
description: FHIRPath navigation and extraction language implemented in pure Dart to be used with base FHIR packages.
publish_to: none
version: 0.12.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_path

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  collection: ^1.19.0
  fhir:
    git: https://github.com/balossi/fhir.git
  ucum: ^0.6.0
  petitparser: ^6.0.2

dev_dependencies:
  lints: ^5.1.1  

